### ISSUE TITLE
Missing script: "dev"

### ISSUE THREAD

**Issue by thefranciscook** [Texterous/LangChainJS-ExpressJS-Boilerplate#1]
I get Missing script: "dev" on npm run dev.
✅ Cloning the repository, installing dependencies, and updating the .env file.

**Comment by thefranciscook** [comment]
Running npm run start solved the issue.

package.json:
```
"scripts": {
    "start": "node index.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  }
```

**Comment by thefranciscook** [comment]
https://github.com/Texterous/LangChainJS-ExpressJS-Boilerplate/pull/2

**Comment by thomasuebi** [comment]
Thank you for contributing and raising a pull request.

**Comment by thefranciscook** [comment]
Thanks for the amazing boilerplate! You rock!
